### ISSUE TITLE
APITool/Swagger: support custom tagger (group by) 

### ISSUE THREAD

**Issue by aclowkey** [jooby-project/jooby#1097]
The motivation of this is to be able to customize The SwaggerBuilder built in ApiTool.java. 

One use case would be to provide grouping functionality. Perhaps there are more, but I think this is useful to support.

**Comment by jknack** [comment]
Hi @aclowkey, this is supported today at two levels:

ApiTool:

```java
{
    use(new ApiTool()
      .modify(r -> r.pattern().equals("/api/pet/{id}", route -> {
        // Fix java doc for id parameter
        route.param("id", param -> {
          param.description("Fixing doc for ID");
        });
        // Set response type
        route.response()
          .type(Pet.class);
      });
    );
  }

}
```

Swagger API:
```java
{
    use(new ApiTool()
      .swagger(swagger -> {
        // Modify swagger resources.
        ...
      })
    );
  }

}
```

See https://jooby.org/doc/apitool/#API-tool-advanced-usage

**Comment by jknack** [comment]
what exactly? Can you share a concrete example?

SwaggerBuilder is an internal class, not a fan of exposing anything there :(

**Comment by jknack** [comment]
Almost all points are fixed in master for script routes:

```
path("/v5/api", () -> {
  path("/song", () -> {
    ...
  });
  path("/album", () -> {
    ...
  });
  path("/artist", () -> {
    ...
  });
});
```

Here the `path` operator defines the  swagger `tag/group`. We should define a similar/default approach for MVC routes.

> Modify Swagger instance - Not good enough, since to group you need to modify the Path's tags, and these Paths aren't loaded at the point where configurer.accept() is called. Calling Swagger.getPaths() would give an empty list

Need to check this, feel callback must run after defaults, so you can actually overwrite something.

Also, there is a custom tag support, but seems I never make it public: https://github.com/jooby-project/jooby/blob/master/modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/SwaggerBuilder.java#L313

Think we are covered with the new tagger (need to define a default for MVC routes) and/or allow user to supply their own tagger.

**Comment by aclowkey** [comment]
> Here the path operator defines the swagger tag/group. We should define a similar/default approach for MVC routes.

This is the code I used for this functionality. I had to rewrite ApiTool and ApiParser in order to get this to work.

> Think we are covered with the new tagger (need to define a default for MVC routes) and/or allow user to supply their own tagger.

I'm not sure what you mean by `define a default for MVC`. Do you mean write a custom tagger that handles MVC route. How is this possible?

Also, I think allowing developers to supply their own tagger is easy and can be useful for very customized tagging behavior.
