### ISSUE TITLE
2.0.2 SSL documentation

### ISSUE THREAD

**Issue by ross-oreto** [jooby-project/jooby#1358]
There is no HTTPS equivalent documentation in version 2.0.2 from 1.x docs

 1.x:
```
application.securePort = 8443

{
  securePort(8443);
}
```

2.x doesn't list anything about HTTPS or SSL from what I can see. Does this server option still exist?

**Comment by jknack** [comment]
No SSL in 2.x and not 100% sure if going to add. SSL in Java is hard

**Comment by danechitoaie** [comment]
Also most likely in prod you will have Nginx or similar in front? As for me running a java/go/etc. (something that provides it's own HTTP server) it's always a problem to expose directly to the internet since on Linux you need root to run apps on ports 80/443 (unless you do some "hacks") so I always end up just putting Nginx in front for HTTPS/load balancing/etc. or deploy somewhere where they do similar things automatically like Heroku/etc.

Not adding arguments inn favor or in opposition to adding HTTPS support to Jooby, just sharing my experience.

**Comment by jknack** [comment]
On that is exactly my experience too. I'm in favor of complete removal of SSL in 2.x or probably will add when all the server implementation (netty, undertow and jetty) handle SSL in the same way with full support at JVM level... otherwise it is a mess and 1.x is an evidence of it

**Comment by ross-oreto** [comment]
Is there a recommended HTTPS setup for deploying to a VM (non container/cloud based environment)?
Would that just be deploying to something like tomcat?

**Comment by agrothe** [comment]
I'm assuming Jooby will still allow us to set the secure flag on cookies. Some libraries stop you from doing that unless you enable SSL.

**Comment by jknack** [comment]
yea, In jooby it is unrelated. will add it to jooby, just need to find a clean way of doing it (not like in 1.x)

**Comment by jknack** [comment]
Doc is available at: https://jooby.io/#server-ssl
