### ISSUE TITLE
application.conf is not read from uber jar using jooby 2.0.3

### ISSUE THREAD

**Issue by humar82** [jooby-project/jooby#1364]
i have packed the application.conf inside the uber jar root directory
and using the following code to read the config

`Environment env = getEnvironment();`
`System.out.println(env.getConfig().getString("foo"));`

Exception in thread "main" com.typesafe.config.ConfigException$Missing: merge of system properties,env variables,defaults: No configuration setting found for key 'foo'

if i place the application.conf in the same directory of the uber jar, the config value can be read.

**Comment by jknack** [comment]
Fixed in 2.0.4. BUT make sure the `application.conf` is part of classpath so maven shade plugin add it to the uber jar.

For example, `conf/application.conf` is NOT part of the classpath, so won't be add it to the uber jar. To fix this you need to:

- configure maven shade to add it
- move `conf/application.conf` to `src/main/resources/application.conf`
