### ISSUE TITLE
Annotations inheritance in MVC routes

### ISSUE THREAD

**Issue by franklx** [jooby-project/jooby#1552]
Annotations on methods of base class are not preserved in children.
```kotlin
open class Base {
    @GET fun get() {}
    @POST fun post() {}
    @GET("{id}") fun get_id(@PathParam id: Int) {}
    @GET @Path("/alt/{id}") fun get_path_id(@PathParam id: Int) {}
}

@Path("/child") class Child: Base() {
    @GET("/children") fun children() {}
}
```
the above code generates:
```
  GET  /child/children
```
in jooby v1 generated:
```
  GET  /child
  POST /child
  GET  /child/{id}
  GET  /child/alt/{id}
  GET  /child/children
```
I wanted to fix it but I'm not really up on annotations processing.

**Comment by franklx** [comment]
Annotations on inherited methods doesn't work because of annotation processing added in jooby-2.x (jooby-1.0 used runtime annotation evaluation).
I developed an utility class that clones inherited methods with attached annotations: https://github.com/franklx/jooby/commit/e29ab99de98e2f2280a9dcdc456f41d2b3506aa5 .
Routes are generated correctly and jooby-2.x behaviour is coherent with 1.x.
I'll write unit tests and then submit a pull request.

**Comment by jknack** [comment]
Cool, will wait for it

**Comment by csisy** [comment]
Sorry to comment on a closed issue, but it seems like it's not working as described in this issue. Example:

```
public class MyClass {

	@Path("concrete")
	public static class ConcreteController1 extends MyAbstractController<Whatever> {}

	public abstract static class MyAbstractController<T> {
	
		@GET
		public List<T> getAll() { ... }
	}
}
```

Te expected behaviour is to have a `GET concrete` endpoint, but instead the startup code throws an exception that 

`io.jooby.Usage: Router not found: [...]. Make sure Jooby annotation processor is configured properly.`

Which is also thrown when no route is found under a given class.
