### ISSUE TITLE
Dev mode: serve assets with Cache-Control: max-age=0

### ISSUE THREAD

**Issue by angryziber** [jooby-project/jooby#1613]
It would be nice to disable browser caching in dev mode by default. 
Many other frameworks do this for convenience.

It is possible programmatically, but rather verbose and almost every project would benefit from it:
```
  assets("/*", AssetHandler(AssetSource.create(Paths.get("public"))).apply {
    if (environment.isActive("dev")) setMaxAge(1)
  })
```

Also note the `setMaxAge(1)` - it doesn't work with `setMaxAge(0)`, while the default value is `-1`.

**Comment by jknack** [comment]
hmm, the etag and last-modified-since header should do it.

**Comment by angryziber** [comment]
Browser caches the resources also in-memory and doesn't do last-modified-since for some time, unless `Cache-Control: must-revalidate` is sent, which is also a good candidate for dev mode.

But I would also change this line to `maxAge >= 0` to support `setMaxAge(0)`:
https://github.com/jooby-project/jooby/blob/95528e0e2e6da6caccdd23fcd1b34baa29b69027/jooby/src/main/java/io/jooby/AssetHandler.java#L106

**Comment by jknack** [comment]
I'm sure browser respects etag and last-modified-since headers. Disabling cache globally for dev won't work for every user. Also, it creates a dependency on "dev" environment and most of user are just not aware of it. Jooby 2.x still keep the concept of environment but not as much as 1.x, we avoid it when possible.

Can you send a PR with setMaxAge(0)?
