### ISSUE TITLE
Feature request : support SSL

### ISSUE THREAD

**Issue by gustvn** [jooby-project/jooby#186]
Production website/web services need more secure

**Comment by paulovictorv** [comment]
If I can leave my +1, it's almost default for the industry today to hide applications behind a load balancer, so supporting SSL at the application level is not really important since all the SSL handling is done at the balancer layer..

However, it's vital to the application code (and framework) to provide support to easily redirect http requests to an https endpoint.

**Comment by jknack** [comment]
agreed. Default is to do it via apache or nginx... but think jooby can do it too.

how do you envision the "provide support to easily redirect http to https"?

**Comment by paulovictorv** [comment]
Something jooby like :)

`` use(new HTTPSRedirect()) ``

or

`` mode(HTTPModes.REDIRECT_SSL) ``

or some configuration: app.prod.conf

`` redirect_to_ssl: true ``

**Comment by jknack** [comment]
done! see http://jooby.org/doc/#https

**Comment by paulovictorv** [comment]
Cool!

And how about the redirect option for those like me that uses a load balancer? :D

**Comment by jknack** [comment]
crap! I missed it!!

**Comment by paulovictorv** [comment]
no worries, will create a new issue for the next release
