### ISSUE TITLE
OpenApi-openapi.json 404

### ISSUE THREAD

**Issue by welkinbai** [jooby-project/jooby#2005]
code:
```
Jooby.runApp(new String[]{}, app -> {
      app.install(new OpenAPIModule("/"));
      app.post("/query", Router::query);
    });
```

result(call http://localhost:8080/redoc): 
Something went wrong...
Error downloading http://localhost:8080/openapi.json HTTP ERROR 404
Stack trace
Error: Error downloading http://localhost:8080/openapi.json 
HTTP ERROR 404
    at http://localhost:8080/redoc/redoc.standalone.js:44:26651
    at http://localhost:8080/redoc/redoc.standalone.js:95:36080

Error: HTTP ERROR 404
    at http://localhost:8080/redoc/redoc.standalone.js:44:26651
    at http://localhost:8080/redoc/redoc.standalone.js:95:35658

ReDoc Version: 2.0.0-rc.40
Commit: 17b9873

**Comment by welkinbai** [comment]
found reason:  
I miss `app.setName("LiveDialogueWebMain"); ` 
so http://localhost:8080/openapi.json will use jooby.json  
Could I directly define openapi.json file name?

**Comment by jknack** [comment]
I see, seems we missed to compute app name there is no inheritance.

> Could I directly define openapi.json file name?

Yea, look here: https://jooby.io/modules/openapi/#openapi-documentation-template

**Comment by welkinbai** [comment]
> I see, seems we missed to compute app name there is no inheritance.
> 
> > Could I directly define openapi.json file name?
> 
> Yea, look here: https://jooby.io/modules/openapi/#openapi-documentation-template

@jknack openapi-documentation-template say file name is conf/openapi.yaml and I can write something about info and server section, how can I assign http://localhost:8080/openapi.json to use LiveDialogueWebMain.json?

**Comment by imeszaros** [comment]
@welkinbai Could you solve it since?

There three paths involved:

- route path to access the metadata like: `http://localhost:8080/yourpath/openapi.json`
  - here you can only customize the `yourpath` part by specifying it when you instantiate the module: `new OpenAPIModule("yourpath")`

- path to the json/yaml file generated by the Jooby Maven/Gradle plugin like: `/YourAppName.json`
  - this file is placed to the classpath automatically when you build the project
  - the file name only depends on the name of your app and you can't change it otherwise

- path of the template file `OpenAPIModule` uses to merge it's content with the generated content when writing the above mentioned file; by default: `/openapi.yaml`
  - conventionally you place this file to the `conf` folder to be available on the classpath
  - you can change the path to this file using `io.jooby.openapi.OpenAPIGenerator#setTemplateName`
