### ISSUE TITLE
Support for Micrometer

### ISSUE THREAD

**Issue by re-thc** [jooby-project/jooby#2188]
Hi, most other libraries have moved onto Micrometer (from Dropwizard metrics) -- Spring, Quarkus, Micronaut, etc... Would be great if Jooby added support for Micrometer as a metrics option.

Thanks for considering!

**Comment by jknack** [comment]
We had have it in 1.x. Would you like to submit a PR?

**Comment by hc-codersatlas** [comment]
How does the current metrics work? It's only for the web server? Or does it tie in with hibernate, hikari etc?

**Comment by imeszaros** [comment]
Hikari module has the capability to register metrics' registries:

https://jooby.io/modules/metrics/

**Comment by agentgt** [comment]
I know this is an old post but I don't recommend Micrometer over Dropwizards Metrics or more so [Open Telemetry](https://github.com/open-telemetry/opentelemetry-java) or [even raw Prometheus](https://github.com/prometheus/client_java)... or yes even JMX.

If one needs diagnostic/infrastructure metrics Open Telemetry is probably best. If one needs business metrics Dropwizard or rolling your own facade is good enough.

Micrometer bills itself as the SLF4j for metrics. You know a facade API but that is not the case at all. Its API jar is 675 kilobytes (both dropwizard metrics and even the complicated open telemetry are 1/6 the size). The reason it is that way is because they packaged the implementation (e.g. window sampling) AND the implementation of collecting metrics from other libraries ALL in one jar.

Furthermore Micrometer does not have healthchecks and forces a static singleton (I don't mind that for logging aka slf4j but I'm not sure I like the idea of every library depending on Micrometer).

Health checks are important k8s liveness and readiness probes. So by switching to micrometer you loose that.
