### ISSUE TITLE
How to redefine CoroutineContext

### ISSUE THREAD

**Issue by cbxp** [jooby-project/jooby#2257]
When using coroutine router, it has a final coroutineScope inside, which is created lazily from worker.

However, there seems to be no easy way to add a CoroutineContext to the scope, e.g. MDCContext from 
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-slf4j/index.html

Could there be a setter for coroutineScope, to enable code like this:

```kotlin
coroutine {
  coroutineScope += MDCContext()

  // routes here
}
```

or another option is to add scope to CouroutineRouter constructor:

```kotlin
coroutine(context = MDCContext()) {
  // routes here
}
```

**Comment by angryziber** [comment]
As a workaround, I found that it is possible to redefine this class in your own project:

```
package io.jooby

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.slf4j.MDCContext
import kotlin.coroutines.CoroutineContext

// TODO: this is a hack to replace Jooby's class in order to modify coroutineContext
class RouterCoroutineScope(coroutineContext: CoroutineContext) : CoroutineScope {
  override val coroutineContext = coroutineContext + MDCContext()
}
```

**Comment by angryziber** [comment]
It seems that for MDCContext() or ThreadLocal transaction passing use-cases adding to the global CoroutineScope would not be enough (the above code does not work because it captures MDC before anything is put there).

It is needed to add something to the CoroutineLauncher, e.g.:

```kotlin
    val coroutineContext = CoroutineExceptionHandler { _, x -> ctx.sendError(x) } + MDCContext() + TransactionCoroutineContext(ctx)
    router.coroutineScope.launch(coroutineContext, router.coroutineStart) {
       ...
    }
```

So there should be a mechanism to provide a new context for each time a coroutine is launched.

Maybe an option would be to provide a lambda for extending the coroutine scope for launch, e.g.:

```kotlin
coroutine {
  launchContext { MDCContext() }

  // routes here
}
```

and then CoroutineLauncher  would run this lambda before it does the `launch`.

**Comment by jknack** [comment]
Hi, would you like to send a PR?

**Comment by angryziber** [comment]
@jknack I can, but which solution would you prefer?

**Comment by jknack** [comment]
I'm not a Kotlin user :(

which one do you like most? or which one is more flexible?

**Comment by cbxp** [comment]
@jknack here you are - PR #2328
