### ISSUE TITLE
OpenAPI not generated with MVC API managed by Spring.

### ISSUE THREAD

**Issue by composite** [jooby-project/jooby#2403]
`jooby:openAPI` is not caught the MVC API managed by Spring.

I'm made a project with jooby 2.10.0, spring boot 2.5.3, and gradle.

Sample project:
[jooby-spring-openapi.zip](https://github.com/jooby-project/jooby/files/6889999/jooby-spring-openapi.zip)

`App.java`
```java
public class App extends Jooby {

  {
    install(new SpringModule());
    install(new OpenAPIModule());
  }

  public static void main(final String[] args) {
    runApp(args, App::new);
  }

}
```

`controller/HomeController.java`
```java
@Controller
@Path("/")
public class HomeController {

    @GET
    public String hello() {
        return "HELLO!";
    }

}
```

`jooby:openAPI` log
```
오후 12:16:57: Executing task 'openAPI'...


> Task :compileJava

> Task :processResources NO-SOURCE
> Task :classes
warning: File for type 'app.controller.HomeController$Module' created in the last round will not be subject to annotation processing.
1 warning
> Task :openAPI

BUILD SUCCESSFUL in 808ms
2 actionable tasks: 2 executed
오후 12:16:59: Task execution finished 'openAPI'.

```

`App.json`

```json
{
  "openapi" : "3.0.1",
  ...
  "paths" : { }
}
```

There is no paths generated in openapi json.

**Comment by agentgt** [comment]
This is because the OpenAPI plugin uses ASM to parse the main Jooby to find all the controllers.

@jknack Since OpenAPI is usually MVC maybe the OpenAPI plugin could look at the META-INF services to find the bytecode generated MVC modules.

A workaround is to just to make a fake Jooby with all of your controllers installed and have the OpenAPI plugin use that.
