### ISSUE TITLE
improve swagger integration

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#252]
we are going to add javadoc from mvc routes and few other improvements like better response types.

also, generation of swagger.json will be done at build time via maven plugin.

see http://jooby.org/doc/swagger

**Comment by paulovictorv** [comment]
Are you planning on defining the routes themselves on a swagger file instead of code, or just generating the swagger file for documentation purposes?

**Comment by jknack** [comment]
swagger file (as today) for doc purposes... but:

1. improve schema responses and param types
2. extract take javadoc and add it to swagger
3. basic/minimal support for inline/embedded routes (probably impossible)

what do you mean by defining routes in swagger? do you have an example? should it generates empty Jooby code from swagger spec?

**Comment by paulovictorv** [comment]
I meant something like the ``routes`` file from Play! Framework:

``
GET   /clients/:id          controllers.Clients.show(id: Long) 
``

It ties the route definition to the method definition.

But now that I think of it, extracting swagger from the routes definition is way smarter than the other way around (create the swagger file first, then from there generate code for the routes).

Are you planning on implementing this in way flexible enough that one can output to custom formats? I was thinking about exporting to ``RAML``, because that's what got defined as a default for my company.
