### ISSUE TITLE
Multiple accept headers

### ISSUE THREAD

**Issue by rafal-kieras** [jooby-project/jooby#2529]
Seems that there is an issue with multiple `Accept` http headers. 

As an example we have the following controller:
```
public class SampleController {
    @GET
    @Path("/hello")
    @Produces("text/plain")
    public String hello() {
        return "Hello world";
    }
}
```

this request works
```
curl --location --request GET 'http://localhost:60611/hello' \
--header 'Accept: text/plain'
```

this one does not
```
curl --location --request GET 'http://localhost:60611/hello' \
--header 'Accept: text/plain' \
--header 'Accept: application/json'
```
it is failing with the following exception
```
io.jooby.exception.TypeMismatchException: Cannot convert value: 'Accept', to: 'java.lang.String'
	at io.jooby.internal.ArrayValue.value(ArrayValue.java:74) ~[jooby-2.13.0.jar:2.13.0]
```

**Comment by csisy** [comment]
There is an additional issue regarding to the accept headers and message encoders.

Let's say we have two message encoders registered to two different media types (e.g. JSON and XML). The `HttpMessageEncoder:99` calls the `encode` function of the next encoder in the list. If an encoder was registered with a media type, then it is wrapped with an `accept` check:

```
@Nonnull default MessageEncoder accept(@Nonnull MediaType contentType) {
  return (ctx, value) -> {
    if (ctx.accept(contentType)) {
      return encode(ctx, value);
    }
    return null;
  };
}
```

However, the `Context::accept` in the `DefaultContext` implementation returns true if the accept header is missing. This defeats the whole purpose of the accept check. Additionally, we can register encoders without specifying the media type. This means that the `encode` method is called directly, and no accept header check is made. This way we can easily register a "fallback" encoder.

Some examples:

```
header: application/json
xml-encoder: does not match -> skip
json-encoder: matches -> use the result
```

```
header: text/plain
xml-encoder: does not match -> skip
json-encoder: does not match -> skip
fallback encoder: no check made -> use the result
```

```
header: <not set>
xml-encoder: matches, because the header is missing -> use the result
```

The expected behaviour would be to use the fallback encoder in this case.

**Comment by jknack** [comment]
Do you mean your last example, right?

Absent of accept header is considered like any response is accepted, so first encoder is used.

**Comment by csisy** [comment]
In my opinion, it would make sense to try to use the "fallback" encoder first that is registered without any `MediaType`. It's not a huge deal however, we can live with the current behaviour. :)
