### ISSUE TITLE
context: Context.lookup + ParamSource

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#3048]
Rename:

```
ctx.lookup().inMultipart() -> ctx.lookup().inForm()
```

Also:

```
ParamSource.MULTIPART => ParamSource.form
```

**Comment by agentgt** [comment]
That annotation change was a little bit more than I expected for bug fix. I guess we are putting Semver aside for the time being while 3.0 is so new.

**Comment by jknack** [comment]
It was a search and replace session, nothing more than that. Same thing here.

> Semver?

I do what I think is best for the project

**Comment by agentgt** [comment]
It’s no problem. Just a surprise.

**Comment by agentgt** [comment]
> It was a search and replace session, nothing more than that. Same thing here.

I can assure you it was more elaborated on my end then that. Had it been a major or even minor release the release notes would have caught my attention and I would have done the search and replace.

Why this didn't get caught like other API changes on our end is I had a custom annotation processor that relied on that annotation enum and for whatever reason it caused bizarre errors that were not smoking gun.

I thought the project was semver. I swore I read it somewhere in the doc but I can't find it so I apologize on that. Besides I have your best interest at heart. Most people expect bug fixes not to break runtime ABI let alone compile time ABI.

> I do what I think is best for the project

Open Source relies on consensus. Most of the consensus on version number particularly dependabot is semver policy.

I can supply links of issues and discussions where folks are a little annoyed with API changes. What person literally said they would not switch from 2.0 to 3.0 if you changed too much API.

If you just want to make up version number changes I'm ok if there is some sort of guideline and I think others will as well because SemVer is kind of broken in general anyway. 

Anyway I gave you an out because its an early major. I totally understand early major versions have API issues and breaking API to fix them is worth it in the long run.

I'm on your side and I'm sorry if the tone sounded jaded... because it was.. it broke our CI pipeline and while it was no big deal it still took more time then simple search replace. I can assure you the jakarta search and replace I did for jooby was not just "search and replace". 

The pro of jooby is way more than this little issue. However others... others get pissed more easily. So I'm just trying to warn and help you.

Anyway I can help on the MVC code generation.
