### ISSUE TITLE
Use KSP for jooby-kotlin instead of KAPT

### ISSUE THREAD

**Issue by Rattlyy** [jooby-project/jooby#3124]
Quoting JetBrains:

> kapt is in maintenance mode. We are keeping it up-to-date with recent Kotlin and Java releases but have no plans to implement new features. Please use the [Kotlin Symbol Processing API (KSP)](https://kotlinlang.org/docs/ksp-overview.html) for annotation processing. [See the list of libraries supported by KSP](https://kotlinlang.org/docs/ksp-overview.html#supported-libraries).

**Comment by jknack** [comment]
Hi,

 where should we use it?

**Comment by Rattlyy** [comment]
for the annotation processor @jknack

**Comment by jknack** [comment]
Do you mean rewrite the two apt processor (MVC and open API) with KSP?

It is impossible to do that effort and maintenance is just too much

**Comment by Rattlyy** [comment]
Hey. Sorry if I stirred a hot pot, but I didn't intend to do so.
I opened this issue to "consider" using KSP, as it's faster and it uses a lot more kotlin-related stuff, so it's better for kotlin projects. KAPT will still continue to be mantained but it won't get any feature updates, so it's fine to use java annotation processors.

 @agentgt Gradle is a lot cleaner and easier to use than maven (xml hell), I made the switch 2 years ago and I haven't really regretted it. It takes some time to get used to it but once you do it's great, especially considering that you have the power of a programming language to define your build process.

**Comment by agentgt** [comment]
@Rattlyy I didn't mean to single you out or even Gradle. I was just trying to show the fragmentation that is happening. If anything I'm shitting on google :)

Gradle the build tool is fine. I has tons of advantages over Maven. I still use Maven more frequently and Maven like Java has improved with things like maven daemon and maven cache extensions.

IntelliJ is a great IDE. I still use JDT for most of my Java development but frequently use IntelliJ.

The problem is JetBrains and Gradle as companies: 

* They are smaller companies that could be potentially acquired or forced to make greater returns. Pseudo open source companies can go bad quickly: lightbend (akka), Hashicorp (terraform), Elastic search etc.
* Smaller companies make drastic hurt ecosystem changes much quicker
* Their primary revenue comes from the lib or tool so money is much more of an agenda than doing the right thing

I'm just tired of learning newer technologies when the above shit happens.

Anyway you can always write a KSP processor as a separate project. I at one point had a partially complete source code generator for Jooby instead of bytecode generator as a separate project.

**Comment by agentgt** [comment]
BTW @jknack have you seen this JEP: https://openjdk.org/jeps/8280389

e.g. ASM -> to Class-File API

Maybe we wait to see what happens there before switching to source code generation?

I haven't had a chance to play with it but it does seem much easier to use than ASM (it still blows my mind in an impressive way how you wrote that byte code generation. I have tried in the past for other project but it is so painful).

**Comment by Rattlyy** [comment]
Closing this as it won't get implemented :)
