### ISSUE TITLE
Chinese characters are garbled

### ISSUE THREAD

**Issue by luminecs** [jooby-project/jooby#3231]
Hello.
I created a jobby project: `jooby create myapp`. But when I use Chinese characters, the return value is garbled.
It should be `Welcome to Jooby!你好`, rather than `Welcome to Jooby!浣犲ソ`. 
Jetty, netty and undertow all have this problem.
Thanks.

```java
public class App extends Jooby {

  {
    install(new JettyServer());
    get("/", ctx -> "Welcome to Jooby!你好");
  }

  public static void main(final String[] args) {
    runApp(args, App::new);
  }

}
```

![image](https://github.com/jooby-project/jooby/assets/24493654/e8ba775c-bd26-4495-8832-e4fe2b9b8576)

**Comment by jknack** [comment]
Hi,

 You need to use UTF_16:

`get("/", ctx -> "Welcome to Jooby!你好".getBytes(StandardCharsets.UTF_16));`

**Comment by agentgt** [comment]
I'll just add to @jknack example because my guess is you want to output it as UTF-8. Also I'm not sure what he provided will work if you didn't paste the chinese characters in correctly.

Java literals and Java files are encoded as UTF-16. When you paste raw unescaped multi-byte characters into Java files they will be read as UTF-16 and not UTF-8. 

However most editor/IDE usually show/manipulate characters as UTF-8. So when you paste Chinese characters in you are putting extra bytes as UTF-8 Chinese characters require more bytes.

I can't test this but some editors/IDE maybe smart enough to do the conversion to UTF-16 when you paste in the letters.

To avoid this what you need to do is put the Chinese characters in some file or template and make sure the characters you paste in are in UTF-8 format.

Then you load the file by bytes and serve it directly or load the file by UTF-8 charset.

**Comment by jknack** [comment]
that is probably why I saw a different output when rendering... thing is that Jooby encoded everything as UTF-8, so not sure why it didn't work. Then, setting UTF-16 encoded properly...

**Comment by agentgt** [comment]
My concern is they may not even have the encoding set for javac. It might be set for UTF-16.

If they set the encoding for UTF-16 it might work.

They talk about this concern with JEP 400: https://openjdk.org/jeps/400

Also they should probably use JDK 21 as I think JDK 18 fixes some issues as UTF-8 is now default... or it could break them even more but they should try upgrading (JDK) anyway.

> The Java language allows source code to express Unicode characters in a [UTF-16 encoding](https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-3.1), and this is unaffected by the choice of UTF-8 for the default charset. However, the javac compiler is affected because it assumes that .java source files are encoded with the default charset, unless configured otherwise by the -encoding [option](https://docs.oracle.com/en/java/javase/16/docs/specs/man/javac.html#standard-options). If source files were saved with a non-UTF-8 encoding and compiled with an earlier JDK, then recompiling on JDK 18 or later may cause problems. For example, if a non-UTF-8 source file has string literals that contain non-ASCII characters, then those literals may be misinterpreted by javac in JDK 18 or later unless -encoding is used.
