### ISSUE TITLE
Open-api does not parse Avaje BeanScope mvc controllers

### ISSUE THREAD

**Issue by kliushnichenko** [jooby-project/jooby#3397]
```java
{
        install(new OpenAPIModule());
        BeanScope beanScope = BeanScope.builder().build();
        mvc(beanScope.get(Controller.class)); // is missing in generated OpenAPI specification 

}
```

**Comment by agentgt** [comment]
I am not sure OpenAPI matters or not for this. The issue is there is no avaje inject module.

See this for integration:

https://github.com/agentgt/petclinic/tree/main/petclinic-config/src/main/java/com/adamgent/petclinic/config/jooby

@jknack and @SentryMan I think we should add an Avaje Inject module as it IMO it is one of the best DI and really fits well into Jooby.
