### ISSUE TITLE
gradle asset plugin

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#414]
Gradle version of [jooby:assets](http://jooby.org/doc/assets)

    gradle joobyAssets

See #312

**Comment by nedtwigg** [comment]
Would be great if `https://github.com/jooby-project/gradle-starter` included a working asset pipeline / livereload setup.

**Comment by jknack** [comment]
can you do it? a new starter project with assets+livereload.

Also, did you see the new frontend module?
http://jooby.org/doc/frontend

**Comment by nedtwigg** [comment]
I did see the new module, very cool!  I asked because I myself couldn't get the asset pipeline to work ;-)  I love the structure of the assets.conf, especially filesets extending each other.

I hacked up the Asset module as it is to work with an external gulp pipeline.  When the thing has matured I'll document it in a blog post, but in the meantime if anyone is interested I'll share the gist of it here:

- [assets.conf](https://github.com/mytake/mytake/blob/856d91605d4d6b2154650ff45a8097f441bd7ee5/server/src/main/resources/assets.conf)
- [CustomAssets](https://github.com/mytake/mytake/blob/856d91605d4d6b2154650ff45a8097f441bd7ee5/server/src/main/java/common/CustomAssets.java#L51-L96)
- [gulpfile](https://github.com/mytake/mytake/blob/856d91605d4d6b2154650ff45a8097f441bd7ee5/client/gulpfile.js)
- [browsersync and hotswap](https://github.com/mytake/mytake/blob/856d91605d4d6b2154650ff45a8097f441bd7ee5/buildSrc/src/main/java/org/mytake/gradle/live/LivePlugin.java)
