### ISSUE TITLE
Debug mode broken since 1.0.0.CR6

### ISSUE THREAD

**Issue by nfleury** [jooby-project/jooby#472]
Using jooby-maven-plugin debug mode does not seems to work anymore since version 1.0.0.CR6

`Listening for transport dt_socket at address: 8000` log does not appear anymore when launching jooby:run and launching remote debug does not work

**Comment by jknack** [comment]
Yes, the change is here: https://github.com/jooby-project/jooby/issues/405

Basically, we don't fork (start a new JVM) anymore. That's why debug mode doesn't work unless:

1. you run `mvnDebug jooby:run` or
2. `mvn jooby:run -Dapplication.fork=true` (this was the default mode in < `.CR6`)

The first option start maven in debug mode on you still have 1 JVM process.

The 2nd option will fork a new JVM. If you find this option better then is probably better to configure the plugin itself:

```xml
<plugin>
  <groupId>org.jooby</groupId>
  <artifactId>jooby-maven-plugin</artifactId>
  <configuration>
    <fork>true</fork>
  </configuration>
</plugin>
```

Make sense?

**Comment by nfleury** [comment]
Ok thanks, yes it totally make sense, but maybe that documentation should be updated with these details here http://jooby.org/doc/devtools/, it still mention that debug is enabled by default when running  

```mvn jooby:run```

That just brings some confusion ... Thanks again !

**Comment by jknack** [comment]
agreed. Pull request are welcome and/or will update soon.

Thanks
