### ISSUE TITLE
Support for .gz compression

### ISSUE THREAD

**Issue by jschneider** [jooby-project/jooby#762]
It would be great to be able to add gz support if the client accepts it.

**Comment by jschneider** [comment]
For Netty:

org.jooby.internal.netty.NettyPipeline:
Probably there should be a way to add something like this:

HttpContentCompressor compressor = new HttpContentCompressor();
pipeline.addLast("httpContentCompressor", compressor);

**Comment by feffi** [comment]
for further questionaire, see last comment in https://github.com/jooby-project/jooby/issues/934

**Comment by marcelstoer** [comment]
This one really hit me by surprise. These days you take it for granted that your favourite web framework supports GZIP - particularly because it's normally a feature of the underlying server/container. This is to say Netty, Jetty and Undertow of course all support it.

Also, I suggest you close #934 for being a duplicate.

**Comment by jknack** [comment]
Fixed in 2.0.0
