### ISSUE TITLE
Who is using Jooby?

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#956]
I would like to know what companies and applications or who are using Jooby.

Thanks all.

**Comment by MrPowerGamerBR** [comment]
I'm using Jooby + Pebble Template Engine for my Discord Bot website: https://loritta.website/

**Comment by jrevault** [comment]
[Navadra](https://www.navadra.com) is powered by Jooby too !!
[https://play.google.com/store/apps/details?id=com.navadra.mmorpg](https://play.google.com/store/apps/details?id=com.navadra.mmorpg)

It's a real serious game. 
Real because, well it's a real RPG with mobs, quests, chests, boss, adventure, story, realm, traitors and deadly rabbits (soon I hope), and we will go MMO in a few months.
Serious because... well there are maths inside for student from 5th grade to 9th grade :)

Bigup for Jooby : center of our world, composed of 3 mobiles apps (1 is live, 2 more will come soon for teachers and parents), a Firebase database for real time app communication, a Google Cloud MySQL database for relational stuffs, and a TimescaleDB for all our stats to keep track of student progression.

But last but not least all the backend has been done in 3 months (started mid-july) by a great team of only ... 1 person 😅 + 4 people working on the Unity 3D game part :)
Deployed on Google Cloud platform, scalability out of the box as Jooby is stateless by nature, nothing to do there, so eaaasyy :)

So no need to say Jooby IS TRULY brilliant to get things done and to stay keep focused on the business code and not the technical part 👍 

Thanx again Jooby team, you rock !!

**Comment by DrorBuhnik** [comment]
[Zeekit](https://zeekit.co)
We use Jooby extensively, our main API backend and all our micro services that have http access uses Jooby
The main API use many Jooby modules (jooq, aws and others), it's auto scale that each instance can peak (today, before marketing) to about 100 req/sec
The other micro services are small in the amount of code and their load

It's great framework to work with, giving you enough room to do your thing without getting in the way and doesn't include "magic" like the big frameworks (spring, play and etc)
It's great that we can use the same framework for both the big backend and the micro services. the footprint is not that big so it's no brainier which one to use when we need a new service

Thank you for all the effort you put in this project!

**Comment by ludmiloff** [comment]
We (our company) use Jooby in API backend with Jdbi, Quartz, Jackson and
some other modules. Sorry, cannot pass a website url. There is a plan to
migrate our frontend too, from php/yii serving 100k users daily to Jooby
with Pebble etc....
Also, I personally have a plan start my own project with Jooby including
backend and frontend, Postgres jdbi3, JWT authentications etc.

Thanks all.

2017-12-05 20:54 GMT+02:00 DrorBuhnik <notifications@github.com>:

**Comment by paul-hammant** [comment]
I'm using Jooby for an online service: [buildradiator.org](https://buildradiator.org) - source - [github.com/BuildRadiator/BuildRadiator](https://github.com/BuildRadiator/BuildRadiator) and really enjoyed the experience.

**Comment by paul-hammant** [comment]
I'm also using Jooby for [https://github.com/paul-hammant/SvnMerkleizer](https://github.com/paul-hammant/SvnMerkleizer) for adding merkle-tree capability to ordinary subversion servers. This was a really quick start-to-finish buildout that was a pure pleasure because of Jooby.

**Comment by AmaranthLIS** [comment]
I used to Jooby for develop Rest API, very comfortable, fast and small jar.
Also created several sites with Jooby + Handlebars + Jongo + Jedis.

**Comment by hwacookie** [comment]
Can't get into details, however, rest assured that jooby is indeed in use :-)
Thank you very much for your work!

**Comment by yholkamp** [comment]
I'm using Jooby for an internal web application.

**Comment by avgx** [comment]
All of my microservices at backend

**Comment by erktime** [comment]
J. Walter Thompson has been writing various projects with Jooby for some time now. We have small web microsites built in it, a few api services built with it, and then our latest endeavor has been a content management system. Jooby has worked well for both smaller and larger projects so far.

**Comment by S66D** [comment]
I used Jooby as conference scheduling and showcase service and used Jooby in raspberry pi as an education hub to serve area with no internet accesses, Jooby promises fast, clean and powerful tool and it  delivers it.

**Comment by nedtwigg** [comment]
We're using Jooby to build MyTake.org - a discussion site for US politics.  Couldn't be happier with Jooby 👍

**Comment by s3cube** [comment]
BookMyShow has been using Jooby for a few projects. With a couple of APIs built using it, it performs as per the requirement.

**Comment by paul-hammant** [comment]
Jooby is used in the "example project" used to describe a best-practice - https://www.branchbyabstraction.com/java.html. It should also 'sell' the brilliant simplicity of Jooby too, IMO.

**Comment by paulovictorv** [comment]
We use Jooby as our default backend framework due to its simplicity regarding implementation, maintenance and operation. Deploy everything in a single jar is dead-ass simple.

www.goclip.com.br is the product that my company develops and it was recently migrated from Play Framework to Jooby. The frameworks are very similar regarding performance (don't have any number to back this up, just my general perception monitoring the app), the main advantage being that it is fully written in Java with no Scala mix and match and weird conventions (global static state, anyone?).

**Comment by kasthomas** [comment]
I only discovered Jooby this morning via a Google-translated Dutch blog (URL forgotten...) and am still evaluating it -- with much excitement. I've looked at Vert.x, Spark, Play, and Spring Boot. Each is strong in particular ways (and weak in particular ways). What I need is a micro-opinionated micro-framework that's powerful yet easy to hack and figure out, with hot-reload and scripting (to shorten dev time). It seems Jooby has hit the sweet spot.

Our Sales team needs an all-in-one executable (fat JAR) they can use to demo our payment peripherals, and as my first proof-of-concept I intend to migrate a Virtual Terminal app I did a year ago (back then it was standard servlets on Jetty). I've been wanting to rewrite the front end of that demo app for some time. (This is a good excuse!) I also have other uses in mind for Jooby, such as hosting interactive tutorials implemented RESTfully. For the apps I have in mind, scalability and performance under load are not issues, but it's good to know the performance is there if I need it later. I like the fact that everything is in a worker thread (fantastic). One of my services will expose a device on the USB bus and I need to know that the polling that goes on in that module won't necessarily clog things up. With Jooby, I have confidence that I'm not heading for trouble.

I work in Documentation and only do development to create example code for customers, create demos, etc. (so, no industrial-strength web apps that need to scale, but rather, proof-of-concept-quality stuff). I have limited time available to do development and have to make every minute count. I can't be bouncing the server 50 times a day or figuring out why some obscure Spring annotation is putting up type-casting warnings, etc. etc. I like that Jooby is explicit about its magic. Spring's magic is way too opaque and covert.

Keep up the good work. I hope your ecosystem grows and you find much success with Jooby. It deserves to succeed.

**Comment by jknack** [comment]
@kasthomas Thank you! <3

**Comment by feffi** [comment]
we at [codecentric](https://www.codecentric.de/) are using jooby and are pretty much into [OpenSource](https://www.codecentric.de/wissen/open-source/) here.

**Comment by alexanderfedinatnasa** [comment]
> I would like to know what companies and applications or who are using Jooby.
> 
> Thanks all.

NASA UTM (https://utm.arc.nasa.gov/) uses Jooby for telemetry RESTful APIs.
Handles pretty well pretty high load.

**Comment by husayt** [comment]
I have been looking for a scalable microframework to use on Google Cloud Run. I have done some POCs and Jooby is very good. You can start with only what you need and then can add features as your needs grow. This way it can stay minimal in size and still very fast, which is the key for serverless deployments.  Will be interesting to see some becnhmarks, how it compares with other frameworks.

**Comment by Sayyiditow** [comment]
Any plans to add thymeleaf to jooby v2? I am considering to move my projects to jooby but the module for thymeleaf is still for v1? Unless these can work interchangeably? Thanks.

**Comment by ToxicMushroom** [comment]
I use it as api for between my website and discord bot https://melijn.com/

**Comment by pierre** [comment]
We use Jooby in a lot of our [Kill Bill](https://killbill.io) plugins. Awesome framework!

**Comment by nedtwigg** [comment]
We're using Jooby 1.x to run https://mytake.org/.  It's a non-profit project where we took all the U.S. presidential debates in history, stuck them into a database, and made it searchable and social-media embeddable.  Working on adding the U.S. Constitution and other unbiased primary sources next. Jooby makes it really easy to focus just on our logic.  We're hoping to find more volunteers so we've put a lot of work into making our dev onboarding easy, if you'd like to see a Jooby 1.x project with hot reload, rocker templates, jOOQ, and postgres-in-docker, here's [our quickstart](https://github.com/mytakedotorg/mtdo/blob/staging/DEV_QUICKSTART.md).

**Comment by paul-hammant** [comment]
Awesome work - [diverging from Jooby advocacy for a sec] do you make your dataset exportable/cloneable?  For example for others to post-process with say JupiterNotebooks for their own epiphanies/charts/wotnot

**Comment by nedtwigg** [comment]
> do you make your dataset exportable/cloneable

Yes!  e.g. https://github.com/mytakedotorg/us-presidential-debates. We also livestream our progress here: https://www.twitch.tv/mytakedotorg

> others to post-process with say JupiterNotebooks for their own epiphanies/charts/wotnot

Hosting these at mytake.org is on [our roadmap](https://github.com/mytakedotorg/mtdo/issues/386).  Just like there is `github.com/paul-hammant`, we hope you would have `mytake.org/paul-hammant`, where you could post your "takes", which are constrained to draw only from verified factsets.  It would be a lot more interesting to read editorialists you disagree with if you at least agreed on the facts.  I don't want to hijack this thread further, but happy to discuss on the mytake.org [issue tracker](https://github.com/mytakedotorg/mtdo/issues), [gitter](https://gitter.im/mytakedotorg), or [forum](https://meta.mytake.org/).  We don't have any funding to speak of (annual budget ~$1k for servers), just a group of stretched-thin volunteers hoping to find more compatriots :)

**Comment by MarcelHB** [comment]
Got curious by spotting it in the top-end of the Techempower Benchmarks. Jooby for lots of small services across our Google AppEngine is really cool: No boilerplate, lots of useful modules, single JAR, probably the fastest comfort zone HTTP service tech I'm currently aware of. :+1:

**Comment by OzzyTheGiant** [comment]
@kasthomas I had been away from Java for a while simply because virtually every project out there was in Spring Boot and I just never got used to the black magic either. Spark was a fun framework to use but it was still gaining traction. Everything else seemed like it wasn't giving a positive development experience. Fast forward to today and the JVM landscape has changed a lot (Kotlin, Java 17, microservices, new frameworks). So I thought I'd give Java another try.

Having said that, @MarcelHB I too saw the latest benchmarks and spotted Jooby near the top. Now I'm currently evaluating Jooby,  Vertx, Quarkus, and Micronaut to see which will be my new default.

**Comment by sillen102** [comment]
Building a whole platform with microservice architecture using Kotlin and Jooby.

**Comment by softprops** [comment]
We use Jooby at meetup.com to host our graphql api which powers all of our external facing products
